import { FarmLevel, Crop, Animal } from './game';

// Farm level configurations
export const FARM_LEVELS: FarmLevel[] = [
  {
    level: 1,
    name: 'Nông Trại Cấp 1',
    requiredExp: 0,
    availableCrops: ['tomato', 'corn'],
    availableAnimals: ['chicken', 'duck'],
    maxSlots: 6,
  },
  {
    level: 2,
    name: 'Nông Trại Cấp 2',
    requiredExp: 1000,
    availableCrops: ['tomato', 'corn', 'carrot', 'lettuce'],
    availableAnimals: ['chicken', 'duck', 'pig', 'cow'],
    maxSlots: 9,
  },
  {
    level: 3,
    name: 'Nông Trại Cấp 3',
    requiredExp: 3000,
    availableCrops: ['tomato', 'corn', 'carrot', 'lettuce', 'pumpkin', 'wheat'],
    availableAnimals: ['chicken', 'duck', 'pig', 'cow', 'sheep', 'horse'],
    maxSlots: 12,
  },
  {
    level: 4,
    name: 'Nông Trại Cấp 4',
    requiredExp: 6000,
    availableCrops: ['tomato', 'corn', 'carrot', 'lettuce', 'pumpkin', 'wheat', 'rice', 'sunflower'],
    availableAnimals: ['chicken', 'duck', 'pig', 'cow', 'sheep', 'horse', 'goat'],
    maxSlots: 15,
  },
  {
    level: 5,
    name: 'Nông Trại Cấp 5',
    requiredExp: 10000,
    availableCrops: ['tomato', 'corn', 'carrot', 'lettuce', 'pumpkin', 'wheat', 'rice', 'sunflower', 'grape', 'apple'],
    availableAnimals: ['chicken', 'duck', 'pig', 'cow', 'sheep', 'horse', 'goat', 'rabbit'],
    maxSlots: 18,
  },
];

// Crop configurations
export const CROPS: { [key: string]: Crop } = {
  tomato: {
    id: 'tomato',
    name: 'Cà Chua',
    icon: '🍅',
    growthTime: 30, // 30 seconds for demo
    expReward: 10,
    sellPrice: 50,
    requiredLevel: 1,
  },
  corn: {
    id: 'corn',
    name: 'Bắp',
    icon: '🌽',
    growthTime: 40,
    expReward: 15,
    sellPrice: 60,
    requiredLevel: 1,
  },
  carrot: {
    id: 'carrot',
    name: 'Cà Rốt',
    icon: '🥕',
    growthTime: 35,
    expReward: 12,
    sellPrice: 55,
    requiredLevel: 2,
  },
  lettuce: {
    id: 'lettuce',
    name: 'Xà Lách',
    icon: '🥬',
    growthTime: 25,
    expReward: 8,
    sellPrice: 40,
    requiredLevel: 2,
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Bí Ngô',
    icon: '🎃',
    growthTime: 50,
    expReward: 20,
    sellPrice: 80,
    requiredLevel: 3,
  },
  wheat: {
    id: 'wheat',
    name: 'Lúa Mì',
    icon: '🌾',
    growthTime: 45,
    expReward: 18,
    sellPrice: 70,
    requiredLevel: 3,
  },
  rice: {
    id: 'rice',
    name: 'Lúa',
    icon: '🍚',
    growthTime: 55,
    expReward: 22,
    sellPrice: 85,
    requiredLevel: 4,
  },
  sunflower: {
    id: 'sunflower',
    name: 'Hoa向日葵',
    icon: '🌻',
    growthTime: 48,
    expReward: 20,
    sellPrice: 75,
    requiredLevel: 4,
  },
  grape: {
    id: 'grape',
    name: 'Nho',
    icon: '🍇',
    growthTime: 60,
    expReward: 25,
    sellPrice: 100,
    requiredLevel: 5,
  },
  apple: {
    id: 'apple',
    name: 'Táo',
    icon: '🍎',
    growthTime: 65,
    expReward: 28,
    sellPrice: 110,
    requiredLevel: 5,
  },
};

// Animal configurations
export const ANIMALS: { [key: string]: Animal } = {
  chicken: {
    id: 'chicken',
    name: 'Gà',
    icon: '🐔',
    productionTime: 20,
    expReward: 8,
    productName: 'Trứng Gà',
    sellPrice: 30,
    requiredLevel: 1,
  },
  duck: {
    id: 'duck',
    name: 'Vịt',
    icon: '🦆',
    productionTime: 25,
    expReward: 10,
    productName: 'Trứng Vịt',
    sellPrice: 40,
    requiredLevel: 1,
  },
  pig: {
    id: 'pig',
    name: 'Lợn',
    icon: '🐷',
    productionTime: 35,
    expReward: 15,
    productName: 'Thịt Lợn',
    sellPrice: 80,
    requiredLevel: 2,
  },
  cow: {
    id: 'cow',
    name: 'Bò',
    icon: '🐄',
    productionTime: 40,
    expReward: 18,
    productName: 'Sữa Bò',
    sellPrice: 100,
    requiredLevel: 2,
  },
  sheep: {
    id: 'sheep',
    name: 'Cừu',
    icon: '🐑',
    productionTime: 30,
    expReward: 12,
    productName: 'Len Cừu',
    sellPrice: 60,
    requiredLevel: 3,
  },
  horse: {
    id: 'horse',
    name: 'Ngựa',
    icon: '🐴',
    productionTime: 45,
    expReward: 20,
    productName: 'Ngựa',
    sellPrice: 150,
    requiredLevel: 3,
  },
  goat: {
    id: 'goat',
    name: 'Dê',
    icon: '🐐',
    productionTime: 28,
    expReward: 13,
    productName: 'Sữa Dê',
    sellPrice: 70,
    requiredLevel: 4,
  },
  rabbit: {
    id: 'rabbit',
    name: 'Thỏ',
    icon: '🐰',
    productionTime: 18,
    expReward: 9,
    productName: 'Thỏ',
    sellPrice: 50,
    requiredLevel: 5,
  },
};
